server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/familytree
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    top.fqq.familytree.dao: debug

pagehelper:
  page-size-zero: true
